### ISSUE TITLE
Serial terminal shows retrieved data but not sent to printer its self

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/ATOM-PRINTER#10]
Ok So this time I now have a stable connection and the terminal show the data being received
```
leng:69
{"Pressure": 99797.74, "Temperature": 23.16281, "Humidity": 61.25582}
home_sensor_data:
leng:69
{"Pressure": 99797.61, "Temperature": 23.21889, "Humidity": 61.28481}
home_sensor_data:
leng:69
{"Pressure": 99803.38, "Temperature": 23.24559, "Humidity": 61.54574}

```

But the data is just not getting printed to the printer.

**Comment by Gitshaoxiang** [comment]
you need to modify the MQTT callback function.  to parse your custom data. then use the printer API to printing.

https://github.com/m5stack/ATOM-PRINTER/blob/master/examples/PRINTER_FW/PRINTER_FW.ino#L95

**Comment by Ajb2k3** [comment]
Alas I am a Micropython/UIFlow user and so have no idea how to do that in arduino.
Sorry.

**Comment by Gitshaoxiang** [comment]
or you could try to publish those data.
TEXT,10,0:{"Pressure": 99803.38, "Temperature": 23.24559, "Humidity": 61.54574}

**Comment by Ajb2k3** [comment]
I tried looking through the API but it makes no sense. I don't know what I'm doing

**Comment by Ajb2k3** [comment]
Ok, took everything back to a clean GitHub download and with my core 2 running this
```
from m5stack import *
from m5stack_ui import *
from uiflow import *
from m5mqtt import M5mqtt
import time
import unit


screen = M5Screen()
screen.clean_screen()
screen.set_screen_bg_color(0xFFFFFF)
env3_0 = unit.get(unit.ENV3, unit.PORTA)






label0 = M5Label('label0', x=12, y=53, color=0x000, font=FONT_MONT_14, parent=None)

def fun_4C_75_25_D7_E3_D1_(topic_data):
  # global params
  label0.set_text(str(topic_data))
  pass


m5mqtt = M5mqtt('printer', 'mqtt.m5stack.com', 1883, 'USER', 'PASSWORD', 300)
m5mqtt.subscribe(str('4C:75:25:D7:E3:D1'), fun_4C_75_25_D7_E3_D1_)
m5mqtt.start()
while True:
  m5mqtt.publish(str('4C:75:25:D7:E3:D1'), str((env3_0.temperature)), 0)
  wait(1)
  wait_ms(2)
```

The printer downloads the data but still doesn't print the data.

**Comment by Gitshaoxiang** [comment]
you need use those block for the printing function

![image](https://github.com/m5stack/ATOM-PRINTER/assets/45260108/a5ad8318-c83d-416e-8db1-e5eee7be392b)

**Comment by Ajb2k3** [comment]
I'm confused, how do you use these blocks when the printer isn't running uiflow?

**Comment by Gitshaoxiang** [comment]
you need to use another device to send the MQTT control msg to the Printer. the Printer just like a slave device.   if you wanna use the UIFlow to control the Printer directly,  you don't need the MQTT function, you could just send the data by UART.

**Comment by Ajb2k3** [comment]
Got it now, thanks.
Now I understand what's happening, I can add it to my project and write a guide.

Thanks, please close.
