### ISSUE TITLE
how to reset printer - WiFi Password Error

### ISSUE THREAD

**Issue by derbuddha** [m5stack/ATOM-PRINTER#3]
how to reset printer to reset new WiFi Password

**Comment by Gitshaoxiang** [comment]
it seems has some bug with this firmware.   you need to erase the flash and upload the firmware again.

**Comment by inajob** [comment]
I faced same probrem.

I modified FactoryTest.ino to reset NVS. So my printer is in AP mode.

add `preferences.putBool("PRINTER_MODE", APMode);` to L80, it force in AP mode.
https://github.com/m5stack/ATOM-PRINTER/blob/3fc76c27a8d344d2d4e70cbb077f0ed5ec8c8fdf/examples/FactoryTest/FactoryTest.ino#L80

But it is just workaround, I think it is FactoryTest.ino 's bug.

**Comment by Gitshaoxiang** [comment]
we just update the example.   It supports starting AP and connecting MQTT at the same time. And supports switching MQTT servers and subscribed topics

[PRINTER_FW](https://github.com/m5stack/ATOM-PRINTER/tree/master/examples/PRINTER_FW)

**Comment by Gitshaoxiang** [comment]
<img src="https://user-images.githubusercontent.com/45260108/152773761-a47d7aee-7894-40c9-8259-13e0f8b7a58c.jpg" width="200px">
