### ISSUE TITLE
add more infos to readme to use MQTT / Example

### ISSUE THREAD

**Issue by derbuddha** [m5stack/ATOM-PRINTER#4]

**Comment by devjulie** [comment]
I agree, their is not a lot of information about getting this working properly. I had to dig around in the source code to find the Client ID that the MQTT app I am using needs (it’s “printer”). Even when it works everything prints on one line, their doesn’t seem to be a way to do a new line with MQTT which makes it useless.

**Comment by TinyuZhao** [comment]
Now you can refer to this example of ours https://github.com/m5stack/ATOM-PRINTER/blob/master/examples/PRINTER_FW/PRINTER_FW.ino
