### ISSUE TITLE
How to change MQTT Server

### ISSUE THREAD

**Issue by RiggsUS** [m5stack/ATOM-PRINTER#5]
I can not find away to change the MQTT server settings, I have tried to compile the source code in VSCode but the build just fails.
We really do need more support for this device is better documentation and more examples that actually work.

**Comment by inajob** [comment]
you check https://github.com/m5stack/ATOM-PRINTER/issues/3#issuecomment-1024839360 .
It is same problem.

**Comment by Gitshaoxiang** [comment]
you could try to use this example. 

[PRINTER_FW](https://github.com/m5stack/ATOM-PRINTER/tree/master/examples/PRINTER_FW)

**Comment by Gitshaoxiang** [comment]
<img src="https://user-images.githubusercontent.com/45260108/152773761-a47d7aee-7894-40c9-8259-13e0f8b7a58c.jpg" width="200px">
