### ISSUE TITLE
Cant Connect to MQTT home server

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/ATOM-PRINTER#8]
Using the code in the repository, I cant connect to my RPI hosted MQTT server. I just get the flashing blue LED and 
```
mqtt_topic: 50:02:91:A0:6C:09
.Connectingreconnect mqtt
.Connecting....reconnect mqtt
```

**Comment by Gitshaoxiang** [comment]
did you have tried to use any MQTT client tools to test with your RPI server?  and it works, right?

**Comment by Ajb2k3** [comment]
Yes, every other device connects to the server and retrieves data

**Comment by Ajb2k3** [comment]
Ok different error here now
`ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
M5Atom initializing...OK
HTTP server started`

**Comment by Ajb2k3** [comment]
Different error now 
```
mqtt.m5stack.com
Connecting....reconnect mqtt
ConnectingE (40858) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (40858) task_wdt:  - IDLE (CPU 0)
E (40858) task_wdt: Tasks currently running:
E (40858) task_wdt: CPU 0: TaskMQTT
E (40858) task_wdt: CPU 1: IDLE
E (40858) task_wdt: Aborting.

abort() was called at PC 0x400e8c61 on core 0


Backtrace: 0x40083d8d:0x3ffbed3c |<-CORRUPTED




ELF file SHA256: dd8bb301109eb333
```

A couple of questions...
1, why is it still connecting to m5stack?

**Comment by Ajb2k3** [comment]
Different message:

```
Get WIFI INFO From Preference
......WiFi Connected!
Get MQTT INFO From Preference
192.168.0.44
mqtt.m5stack.com
ConnectingMQTT Connected!
 success
subscribe: 50:02:91:A0:6C:09
```

Where is it calling **mqtt.m5stack.com** I cant find a reference to it anywhere?

Should it be requesting data from the server or should the server be sending the data?

My MQTT stream is : home_sensor_data

**Comment by Gitshaoxiang** [comment]
in this line use the MQTT server config.  

https://github.com/m5stack/ATOM-PRINTER/blob/master/examples/PRINTER_FW/PRINTER_FW.ino#L125

**Comment by Gitshaoxiang** [comment]
also.  we just update the example and fix some issues. you could test it again, thanks
